# docker-compose.yml
version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: driver_profile
    ports: ["5438:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
  api:
    build: .
    env_file: .env
    ports: ["3001:3000"]
    depends_on: [db]
volumes: { pgdata: {} }
